version: 2
updates:
  # Enable version updates for pub dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "NewChoBo"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for pub dependencies in example
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "NewChoBo"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "NewChoBo"
    commit-message:
      prefix: "ci"
      include: "scope"
