name: display_identify_overlay
description: >
  A Flutter package that displays monitor index numbers as overlays on all
  connected displays. Perfect for identifying monitors in multi-display setups.
version: 0.1.0
publish_to: none
homepage: https://github.com/NewChoBo/display_identify_overlay
repository: https://github.com/NewChoBo/display_identify_overlay
issue_tracker: https://github.com/NewChoBo/display_identify_overlay/issues
license: MIT

keywords:
  - monitor
  - display
  - overlay
  - multi-monitor
  - desktop
  - windows
  - flutter-plugin

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

platforms:
  windows:
  linux:
  macos:

flutter:
  plugin:
    platforms:
      windows:
        default_package: display_identify_overlay_windows
      linux:
        default_package: display_identify_overlay_linux
      macos:
        default_package: display_identify_overlay_macos

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  win32: ^5.4.0
  display_identify_overlay_platform_interface:
    path: packages/display_identify_overlay_platform_interface
  display_identify_overlay_windows:
    path: packages/display_identify_overlay_windows
  display_identify_overlay_linux:
    path: packages/display_identify_overlay_linux
  display_identify_overlay_macos:
    path: packages/display_identify_overlay_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  coverage: ^1.6.3
