name: display_identify_overlay_windows
version: 0.1.0
publish_to: none
description: Windows implementation of the display_identify_overlay federated plugin.

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: display_identify_overlay
    platforms:
      windows:
        dartPluginClass: DisplayIdentifyOverlayWindows

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  win32: ^5.4.0
  display_identify_overlay_platform_interface:
    path: ../display_identify_overlay_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
